# Generated by Django 5.2.7 on 2025-11-14 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cheque', 'Cheque')], max_length=20)),
                ('payment_date', models.DateField()),
                ('receipt_photo', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenanceticket')),
                ('property_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.expensecategory')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('rent', 'Rent'), ('security_deposit', 'Security Deposit'), ('stamp_duty', 'Stamp Duty'), ('utility', 'Utility Bill'), ('late_fee', 'Late Fee'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=200)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('rent_month', models.DateField(blank=True, null=True)),
                ('is_rent_paid', models.BooleanField(default=False)),
                ('late_fee_days', models.IntegerField(default=0)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_generated', models.BooleanField(default=False)),
                ('receipt_generated_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('proof_verified', models.BooleanField(default=False)),
                ('proof_verified_date', models.DateTimeField(blank=True, null=True)),
                ('proof_verification_notes', models.TextField(blank=True)),
                ('proof_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs Clarification')], default='pending_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('proof_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('bill_photo', models.FileField(blank=True, null=True, upload_to='utility_bills/')),
                ('is_allocated', models.BooleanField(default=False)),
                ('allocation_date', models.DateTimeField(blank=True, null=True)),
                ('total_allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tenants', models.IntegerField(default=1)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
