# Generated by Django 5.2.7 on 2026-02-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_key_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_non_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_security_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_stamp_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_notes',
            field=models.TextField(blank=True),
        ),
    ]
