# Generated by Django 5.2.7 on 2025-11-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilitybill',
            old_name='property',
            new_name='property_obj',
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='allocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='total_allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
