# Generated by Django 5.2.7 on 2025-12-27 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('booking', 'Booking Inquiry'), ('general', 'General Inquiry'), ('maintenance', 'Maintenance Issue'), ('job_application', 'Job Application'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('room_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('desired_position', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], max_length=20)),
                ('available_from', models.DateField()),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(upload_to='job_applications/resumes/')),
                ('cover_letter', models.FileField(blank=True, upload_to='job_applications/cover_letters/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Wing Kong Property Management', max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(default='info@wing-kong.com', max_length=254)),
                ('contact_phone', models.CharField(default='+852 1234 5678', max_length=20)),
                ('address', models.TextField()),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('min_stay_months', models.IntegerField(default=3)),
                ('max_stay_months', models.IntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('feedback_type', models.CharField(choices=[('testimonial', 'Testimonial'), ('review', 'Review'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion')], max_length=20)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('approved', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
