# Generated by Django 5.2.7 on 2025-10-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_temporary_stay_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='permanent_stay_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rent for permanent room', max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='rent_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive = refund, Negative = additional payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='temporary_stay_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rent during temporary stay', max_digits=10),
        ),
    ]
