# Generated by Django 5.2.7 on 2025-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_is_temporary_stay_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='move_out_notice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='move_out_notice_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_status',
            field=models.CharField(choices=[('not_sent', 'Renewal Not Sent'), ('sent', 'Renewal Sent'), ('renewed', 'Renewed'), ('declined', 'Declined')], default='not_sent', max_length=20),
        ),
    ]
