# Generated by Django 5.2.7 on 2025-11-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_move_out_notice_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/pdfs/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='digital_signature_staff',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='digital_signature_tenant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='contract',
            name='staff_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='whatsapp_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
