# Generated by Django 5.2.7 on 2025-10-16 17:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('building', 'Building')], max_length=20)),
                ('total_rooms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('room_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('temporary', 'Temporary Stay')], default='available', max_length=20)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_private_bathroom', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'ordering': ['room_code'],
            },
        ),
    ]
