# Generated by Django 5.2.7 on 2025-10-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('temporary', 'Temporary Stay'), ('cleaning', 'Being Cleaned')], default='available', max_length=20),
        ),
    ]
