# Generated by Django 5.2.7 on 2025-11-15 12:39

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='room',
            name='videos',
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.room_photo_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='properties.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=properties.models.room_video_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_videos', to='properties.room')),
            ],
        ),
    ]
