# Generated by Django 5.2.7 on 2025-11-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_room_photos_remove_room_videos_roomphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_in_china',
            field=models.TextField(default=(('apartment', 'Apartment'),)),
            preserve_default=False,
        ),
    ]
