# Generated by Django 5.2.7 on 2025-10-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('management_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('management_fee', models.DecimalField(decimal_places=2, help_text='Monthly management fee', max_digits=10)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('monthly_rent_to_owner', models.DecimalField(decimal_places=2, help_text='Monthly rent paid to owner', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_rent_paid_date', models.DateField(blank=True, null=True)),
                ('next_rent_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ownerships', to='properties.owner')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ownerships', to='properties.property')),
            ],
        ),
    ]
