# Generated by Django 5.2.7 on 2025-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_address_in_china'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address_in_china',
        ),
        migrations.AddField(
            model_name='property',
            name='address_chinese',
            field=models.TextField(blank=True, null=True),
        ),
    ]
