# Generated by Django 5.2.7 on 2025-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_owner_propertyownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='post_ad_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price advertised to public (for rent increase detection)', max_digits=10, null=True),
        ),
    ]
