# Generated by Django 5.2.7 on 2025-11-15 17:33

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_address_in_china_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.property_image_upload_path)),
                ('image_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('toilet', 'Toilet'), ('street_level', 'Street Level'), ('other', 'Other')], max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary image for this type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='properties.property')),
            ],
            options={
                'ordering': ['image_type', '-is_primary', 'uploaded_at'],
            },
        ),
    ]
