# Generated by Django 5.2.7 on 2025-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_actual_move_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='move_out_clean_status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('clean', 'Clean - Ready for Refund'), ('needs_cleaning', 'Needs Additional Cleaning'), ('damages', 'Damages Found')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='move_out_inspection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='move_out_inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='move_out_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Refund Pending'), ('processing', 'Refund Processing'), ('completed', 'Refund Completed'), ('deductions', 'Refund with Deductions')], default='pending', max_length=20),
        ),
    ]
