# Generated by Django 5.2.7 on 2025-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('rent_reminder', 'Rent Reminder'), ('contract_reminder', 'Contract Reminder'), ('birthday_wish', 'Birthday Wish'), ('late_fee_invoice', 'Late Fee Invoice'), ('move_out_reminder', 'Move Out Reminder'), ('rent_increase', 'Rent Increase Notice'), ('test_notification', 'Test Notification')], max_length=50),
        ),
    ]
